input_shape : (28, 28, 1)
base_depth : 16
encoded_size : 10
batch_size : 128
epochs : 10
optimizer : "Adam"
loss : "mse"
learning_rate : 1e-3
metrics : "mse"
path_model : "./"
variational : False
distribution : "Bernoulli"